default:
  image: debian:sid
  before_script:
    - apt-get update
    - apt-get -y install build-essential gawk git libncurses-dev lua-check python2 shellcheck time unzip wget
    - rm -rf ../gluon
    - git clone https://github.com/freifunk-gluon/gluon.git ../gluon
    - cd ../gluon
    - git checkout v2020.2.3
    - ln -s ../site-ffc site

stages:
  - lint
  - build

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH != "$CI_DEFAULT_BRANCH"'

check-siteconf:
  stage: lint
  script:
    - make lint-lua
    - make lint-sh

build-gluon:
  image: debian:buster
  stage: build
  tags: [gluon]
  variables:
    BROKEN: 1
    FORCE_UNSAFE_CONFIGURE: 1
  parallel:
    matrix:
      - GLUON_TARGET: [ar71xx-generic, ar71xx-tiny, ar71xx-nand, ath79-generic, brcm2708-bcm2708, brcm2708-bcm2709, ipq40xx-generic, ipq806x-generic, lantiq-xrx200, lantiq-xway, mpc85xx-generic, mpc85xx-p1020, ramips-mt7620, ramips-mt7621, ramips-mt76x8, ramips-rt305x, sunxi-cortexa7, x86-generic, x86-geode, x86-legacy, x86-64, ar71xx-mikrotik, brcm2708-bcm2710, mvebu-cortexa9]
  script:
    - make update
    - make -j$(nproc || printf 2)
